### PR TITLE
updates

### PR DESCRIPTION
**Pull request by nmoorenz**
This is a really good resource so hopefully these are helpful edits for spelling and grammar.

### CODE REVIEW

**Comment by EdwinTh** [comment]
Many, many thanks for your effort. Much appreciated. 

It seems that you made the changes on an older version of master (I did some editing myself the last days). Would you mind to update from master so the changes can be merged? Thanks!

**Comment by nmoorenz** [comment]
Yes, I can do this. I don't think it's possible to fetch on GitHub.com (I just did edits in the browser) but I'll clone and do it properly. I was hoping you could just merge.

**Comment by EdwinTh** [comment]
Thanks, I will not touch anything until you are done.

**Comment by nmoorenz** [comment]
closing since I think I've done it properly this time.

**Pull request closed without merging**
