### PR TITLE
Edit intro / index.rmd

### PR DESCRIPTION
**Pull request by tweed1e**
Hi! I did some English editing / fixing typos on the Introduction in index.Rmd, I hope this helps, feel free to change anything you like.

### CODE REVIEW

**Comment by EdwinTh** [comment]
Thanks a lot! I just realised that it is difficult to track changes with the Rmarkdown format where a full paragraph is on a single line. Will look into as soon I have a little time.

**Comment by tweed1e** [comment]
Np! Happy to do more editing if .rmd track changes can work well on here

**Comment by EdwinTh** [comment]
Used almost all your suggestions in commit 73, not merging this one. Thanks again!

**Comment by EdwinTh** [comment]
FYI, I found out that you can place every new line on a separate line and Rmarkdown still prints them continuously. I will update all the existing chapters so we can keep doing pull requests.

**Comment by tweed1e** [comment]
> FYI, I found out that you can place every new line on a separate line and Rmarkdown still prints them continuously. I will update all the existing chapters so we can keep doing pull requests.

Great! I'm happy to help edit when I have the time. 👍👍

**Pull request closed without merging**
